### PR TITLE
Added support for non-https scheme.

### PR DESCRIPTION
**Pull request by iAndriy**

### CODE REVIEW

**Comment by iAndriy** [comment]
@xavivars Hey, that will allow handler to talk in http format, for example usage of mock servers to substitute sumopy endpoint over http (usually they work in http mode).

**Review by xavivars — APPROVED** [review]
Thanks a lot! Didn't really know anyone else was actually using this 😅

**Comment by iAndriy** [comment]
@xavivars yeah, thanks for writing that package and thanks for fast review. Can we make it available in pypi ?

**Comment by xavivars** [comment]
@iAndriy should be there :)

**Pull request merged**
